### ISSUE TITLE
Compilation errors post upgrade from v 0.0.6 to 0.1.0

### ISSUE THREAD

**Issue by ravivit9** [codediodeio/geofirex#90]
Please find attached error screenshot after upgrading geofirex from v 0.6.0 to 0.1.0

    "firebase": "^7.6.0",
    "firebaseui": "^4.3.0",
    "geofirex": "0.1.0",

Downgraded for now for the app to work.

**Comment by ravivit9** [comment]
<img width="1215" alt="Screenshot 2019-07-29 at 19 21 46" src="https://user-images.githubusercontent.com/3435829/70853989-9c610180-1ead-11ea-8742-39a3cf7651b9.png">

**Comment by ravivit9** [comment]
<img width="1389" alt="Screenshot 2019-12-14 at 20 01 05" src="https://user-images.githubusercontent.com/3435829/70853999-bbf82a00-1ead-11ea-860c-e90716209dd1.png">

**Comment by ravivit9** [comment]
Hi,  Appreciate if anyone could help to sort out or cause for the above errors.

Thanks.

**Comment by ravivit9** [comment]
@codediodeio, Updated the version no in the summary title.

**Comment by ravivit9** [comment]
Adding package.json information

```{
  "name": "gio-cabs",
  "author": {
    "name": "Ravindra Bharathi",
    "email": "Ravindra.Bharathi@outlook.com",
    "url": "https://gio-cabs.com"
  },
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build-prod": "ng build --aot --prod",
    "www-build": "ng build --prod --base-href . --output-path www",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "bundle-report": "webpack-bundle-analyzer dist/gio-cabs/stats.json"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.1.0",
    "@angular/animations": "^8.2.14",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "^8.2.14",
    "@angular/compiler": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/fire": "^5.2.3",
    "@angular/flex-layout": "^8.0.0-beta.27",
    "@angular/forms": "^8.2.14",
    "@angular/http": "^7.2.15",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/router": "^8.2.14",
    "@ngrx/store": "^8.6.0",
    "@types/cordova": "0.0.34",
    "@types/googlemaps": "latest",
    "agm-direction": "^0.7.9",
    "cordova-android": "^8.1.0",
    "cordova-browser": "^6.0.0",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-geolocation": "^4.0.2",
    "cordova-plugin-request-location-accuracy": "^2.3.0",
    "cordova-plugin-whitelist": "^1.3.4",
    "cordova.plugins.diagnostic": "^5.0.1",
    "core-js": "^3.6.1",
    "emulator": "^0.1.0",
    "firebase": "^7.6.1",
    "firebaseui": "^4.4.0",
    "geofirex": "0.0.6",
    "geolocation-utils": "^1.2.2",
    "hammerjs": "^2.0.8",
    "ngx-google-places-autocomplete": "^2.0.4",
    "ngx-webstorage-service": "^4.1.0",
    "rxjs": "^6.5.4",
    "rxjs-compat": "^6.5.4",
    "tslib": "^1.10.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "^0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.21",
    "@angular/cli": "~8.3.21",
    "@angular/compiler-cli": "^8.2.14",
    "@angular/language-service": "^8.2.14",
    "@types/jasmine": "^3.5.0",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "^13.1.1",
    "codelyzer": "^5.2.1",
    "husky": "^3.1.0",
    "jasmine-core": "^3.5.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^4.4.1",
    "karma-chrome-launcher": "^3.1.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "~2.1.1",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.5.1",
    "prettier": "^1.19.1",
    "pretty-quick": "^2.0.1",
    "protractor": "^5.4.2",
    "rxjs-tslint": "^0.1.7",
    "ts-node": "~8.5.4",
    "tslint": "^5.20.1",
    "typescript": "3.5.3",
    "webpack-bundle-analyzer": "^3.6.0"
  },
  "husky": {
    "hooks": {}
  },
  "cordova": {
    "platforms": [
      "android",
      "browser"
    ],
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-geolocation": {}
    }
  }
}
```

**Comment by ravivit9** [comment]
@codediodeio hope the above helps to identify whether I am using an incompatible library in the view of  geofirex.

Thanks.

**Comment by jasonc624** [comment]
Geofirex is not compatible with higher versions of firebase i guess anything above 7.1.x.
